- requirements-devel.txt
- setup.cfg
Fixes issue #105 
This PR does two things:
- add missing requirements to `requirements-devel,txt`. This file is used in the CI-tests
- update the datalad-metalad minimum version to include a recent bugfix
> Add missing requirements and updated versions

- datalad_catalog/catalog.py
- datalad_catalog/meta_item.py
- datalad_catalog/webcatalog.py
This restructures and rewrites Python import statements
to better comply to DataLad Core's design document at
http://docs.datalad.org/en/stable/design/python_imports.html.
I have decided to resolve relative imports completely - but
this decision is more personal taste and can be debated.
Fixes https://github.com/datalad/datalad-catalog/issues/108
> MNT: Make import statements comply to design doc

- docs/source/installation.rst
Updates the installation instructions to be inline with the `README` and adds information on the dependencies.
Towards #103
> DOC: update installation instructions

- datalad_catalog/catalog.py
- datalad_catalog/tests/test_catalog.py
This PR adds tests for 'datalad_catalog/catalog.py' and refactors `datalad_catalog/catalog.py`, using the tests to verify integrity of the code.
> Add tests for datalad_catalog/catalog.py and refactor tested module

- datalad_catalog/catalog/assets/vue_app.js
The `Date.prototype.getMonth()` returns a zero-based value ([docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getMonth)), similar to `Date.prototype.getDay()` (day of the week, not used here) but different from `Date.prototype.getDate()` (day of the month, 1-31). So we need to add one to month (but not day and year).
Alternatively, we could get date string with `d.toISOString().substring(0,10)`
Fixes #90
> FIX: Adjust month in getDateFromUTCSeconds

- docs/source/usage.rst
This adds a basic description of the main commands necessary for generating a catalog.
Towards #103
> DOC: add content to the usage page

- datalad_catalog/catalog.py
Previously, progress bars were neither properly created nor removed
for metadata validation (#136). This change is oriented on
docs.datalad.org/en/latest/design/progress_reporting.html and creates,
updates, and removes the progress bar as outlined in the design docs.
Fixes #136
> ENH: Orderly create, update, and take down validation progress bars

- datalad_catalog/catalog.py
- datalad_catalog/meta_item.py
- datalad_catalog/tests/test_multisource.py
- datalad_catalog/tests/test_node.py
- datalad_catalog/tests/test_translate.py
- datalad_catalog/webcatalog.py
This PR addresses #168 and #169.
It refactors the code in multiple modules related to how and when metadata is read from and written to target files in a catalog. Main changes include:
- The `MetaItem` class, responsible for translating an incoming json line metadata item into catalog metadata consisting of one or multiple `Node`s (each with a corresponding json file), can be the parent of multiple `Node` instances.
- New functionality for (1) creating a new node if the corresponding file does not yet exist, and (2) reading a node's attributes from file if the file already exists. This is done whenever the `Node` class is instantiated.
- At the end of processing a single `MetaItem` instance, its children nodes are written to file, instead of all nodes being written to file at the end of …
> ENH: refactor read+write process of catalog metadata

- CHANGELOG.md
- setup.cfg
To address `FileNotFoundError` and related errors in `datalad-extensions` workflow runs, see https://github.com/datalad/datalad-catalog/issues/198.
> Adds test data to package_data

- datalad_catalog/catalog/assets/style.css
- datalad_catalog/catalog/assets/vue_app.js
- datalad_catalog/catalog/index.html
This PR closes #44 and #52.
The main decisions and implementations:
- in the subdatasets view: keep the listed subdatasets as they are, i.e. only list the subdatasets that are also available in the same catalog (no changes made here)
- in the file tree view: keep and display the unavailable subdatasets, but grey them out (changed). These items are not clickable anymore and hence there is no need to show a popup for unavailable subdatasets (unless subdataset metadata that *should* be available in the catalog is not available for some other reason)
> ENH: handling of unavailable subdatasets in file browser

- datalad_catalog/catalog/assets/meta_entry.js
- datalad_catalog/catalog/assets/style.css
- datalad_catalog/catalog/metadata-entry.html
The point is to have a (currently hidden) page on which users can enter metadata. This content then populates fields on an object, and the object is downloaded as a json file upon submit.
In future, this functionality can be extended to generate form fields automatically from a schema.
> Adds simplistic demo for metadata entry

- datalad_catalog/catalog/assets/display_schema.js
- datalad_catalog/catalog/assets/jsonschema_dataset.json
- datalad_catalog/catalog/assets/style.css
- datalad_catalog/catalog/display_schema.html
This PR:
- adds initial code to auto-render a human readable version of a json-schema definition, in this case for the catalog's `dataset` schema.
- addresses the basics of https://github.com/datalad/datalad-catalog/issues/74 for `dataset` schema in particular
- puts the first part of the code in place in order to auto-generate a form from json-schema, towards addressing https://github.com/datalad/datalad-catalog/issues/204 (see here in relation to gooey: https://github.com/datalad/datalad-gooey/issues/329)
- compatible with [jsonschema draft 2020](https://json-schema.org/draft/2020-12/release-notes.html) (mostly...)
Remaining challenges:
- the current setup ignores schema references. References would need to be resolved and aggregated into the top-level schema in order to be rendered by …
> NF: Render a human-readable json schema definition

- datalad_catalog/catalog/assets/display_schema.js
- datalad_catalog/catalog/assets/jsonschema_authors.json
- datalad_catalog/catalog/assets/jsonschema_catalog.json
- datalad_catalog/catalog/assets/jsonschema_dataset.json
- datalad_catalog/catalog/assets/jsonschema_extractors.json
- datalad_catalog/catalog/assets/jsonschema_file.json
- datalad_catalog/catalog/assets/style.css
- datalad_catalog/catalog/display_schema.html
This PR extends https://github.com/datalad/datalad-catalog/pull/216 to include:
- all `datalad-catalog` schemas
- resolving of references by locating a `$ref` value in the list of `$id`s of all locally loaded schemas
> ENH: make schemas selectable; resolve local refs via '$id'

- README.md
- docs/source/catalog_schema.rst
- docs/source/index.rst
- docs/source/installation.rst
- docs/source/metadata_formats.rst
- docs/source/overview.rst
- docs/source/usage.rst
This PR:
- updates docs and readme to include references to the rendered [catalog schema](https://datalad.github.io/datalad-catalog/display_schema.html)
- closes #74
> DOC: catalog schema rendering

- .appveyor.yml
Prevents homebrew from stalling while "macOS" currently resolves to outdated Catalina. Fixes #241
> Switch MacOS Appveyor builds to Monterey

- datalad_catalog/extractors/datacite_gin.py
- setup.cfg
The `datalad.metadata` module was removed from DataLad 0.18 and added to MetaLad 0.4.6. It was imported only once in the catalog codebase (and only to get a single constant). Switching the import will restore compatibility with datalad 0.18.
This also bumps the required patch version of Metalad.
Fixes #238 and should resolve #239.
Note, there are still two matches within the catalog module:
```
❱ git grep datalad.metadata
extractors/datacite_gin.py:lgr = logging.getLogger("datalad.metadata.extractors.datacite_gin")
workflows.py:    return _describe_metadata_elements("datalad.metadata.extractors")
```
The second is I think OK, as it refers to entry point name. Not sure about the first, whether the logger should be renamed to `datalad.catalog.extractors.datacite_gin` or whether it's …
> BF: Remove imports of datalad.metadata

- conftest.py
- datalad_catalog/tests/test_workflow.py
- setup.cfg
`jq` building is failing on windows during appveyor testing.
- Tried `--ignore=` and `--ignore-glob=` flags unsuccessfully in appveyour `cmd` calls.
- Tried using `git-bash` unsuccessfully.
This PR ensures:
- `jq` is not installed on windows (add below to `setup.cfg`)
```
install_requires
jq;platform_system!='Windows'
```
- that the `workflows.py` module and related `test_workflow.py` are not collected by pytest on windows (added `conf.py` with content below:)
```python
import platform
if platform.system() == 'Windows':
collect_ignore_glob = ["*workflow.py", "*workflows.py"]
```
> ENH: don't install jq dependency on windows

- datalad_catalog/translators/bids_dataset_translator.py
- datalad_catalog/translators/metalad_core_translator.py
- datalad_catalog/webcatalog.py
- Closes https://github.com/datalad/datalad-catalog/issues/262 by adding file-level translation to `metalad_core`
- Fixes `bids_dataset` translator bug
- Ensures that a logo path provided via config file resolves correctly
> ENH+BUG: Improving translators and catalog generation.

- datalad_catalog/catalog/assets/app_component_dataset.js
- datalad_catalog/catalog/assets/app_component_item.js
- datalad_catalog/catalog/assets/app_component_notfound.js
- datalad_catalog/catalog/templates/dataset-template.html
- datalad_catalog/catalog/templates/item-template.html
Enhancements and bug fixes of several UX aspects.
Specifically:
- Closes https://github.com/datalad/datalad-catalog/issues/263
- Closes https://github.com/datalad/datalad-catalog/issues/208
- Closes https://github.com/datalad/datalad-catalog/issues/268
- Closes https://github.com/datalad/datalad-catalog/issues/271
> Frontend maintenance

- datalad_catalog/translators/bids_dataset_translator.py
In BIDS 1.8.0 and earlier, dataset_description.json has "Name" and "License" keys, and both fields are strings. The [bids_dataset](https://github.com/datalad/datalad-neuroimaging/blob/master/datalad_neuroimaging/extractors/bids_dataset.py) extractor from datalad-neuroimaging keeps these key names.
This PR fixes the field lookup, and also includes the license in the translated output.
The change also lets the extractor add license url for "PDDL" and "CC0" (the two are named explicitly in bids spec, others are allowed but at least we give the two a chance to get translated with a proper URL).
> Bids translator - fix name & license reporting

- datalad_catalog/catalog/assets/app_component_dataset.js
- datalad_catalog/catalog/assets/app_router.js
- datalad_catalog/catalog/templates/dataset-template.html
This PR addresses https://github.com/datalad/datalad-catalog/issues/293
Mainly:
- it is now possible to specify the tab name (e.g. `subdatasets`, `content`, `publications`, etc) as a URL parameter and navigation will ensure that the corresponding tab is opened when opening the dataset page. If a corresponding tab does not exist, the first tab is opened (subdatasets; whether the dataset has subdatasets or not.)
- if a dataset has no subdatasets or content, the next available tab will open when the page is viewed
> ENH: URL parameterization

- datalad_catalog/catalog/assets/app_component_dataset.js
- datalad_catalog/catalog/templates/dataset-template.html
This PR fixes:
- #298 
- #297 
- Change license and doi states to "unknown" instead of "unavailable"
- Rephrase "search" to "filter"
- Strips white space and newline characters from copied clone command
- Hide dataset properties if their value == 0, specifically `Subdatasets`, but also works for other properties
Refer to items in this issue for more context: https://github.com/datalad/datalad-catalog/issues/296
> BUG/ENH/UX: lots of JS tweaks

- datalad_catalog/extractors/tests/test_datacite_gin.py
- datalad_catalog/tests/register.py
- datalad_catalog/tests/test_catalog.py
- datalad_catalog/tests/test_catalog_arguments.py
- datalad_catalog/tests/test_translate.py
- docs/source/conf.py
- requirements-devel.txt
- setup.cfg
As datalad-catalog now uses pytest instead of nose, it should be importing test utilities from `datalad.tests.utils_pytest` instead.
> Update datalad.tests.utils imports

- datalad_catalog/tests/data/workflow_generated_meta_sub.json
- datalad_catalog/translators/datacite_gin_translator.py
This is a small tweak to `datacite_gin_translator` that will:
- Use a case-insensitive replacement (accepting both "doi:" and "DOI:" prefix in translated metadata)
- Return the DOI as `https://doi.org/...` (no www) because this is the format expected by the catalog for nice rendering
- Adjust tests accordingly
FMPOV this should be enough to close #322 as it answers the original problem -- unless you do want to add more formatting rules to JS.
Ping https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/23
> Fix datacite_gin publication doi translation

- datalad_catalog/set.py
- datalad_catalog/tests/test_set.py
- datalad_catalog/tests/test_validate.py
- datalad_catalog/validate.py
Just a couple of basic fixes and additional tests to fix issues that @mslw encountered during usage
- closes #330 
- closes #331
> [BF] Small fixes to latest cli commands

- CHANGELOG.md
- readthedocs.yml
- Depend on `next 1.0.0b3`
- Add config file for readthedocs
- update changelog
> Depend on `next` 1.0.0b3

- CONTRIBUTORS
> [FIX] Remove contributors file

- datalad_catalog/catalog/assets/app_component_item.js
The previous state resulted in  the download url for a file only containing the first letter of a string (i.e. `url_string[0]`) because it tested for the existence of an array incorrectly. This PR fixes that test and closes https://github.com/datalad/datalad-catalog/issues/342
> BF: fix file download url rendering

- datalad_catalog/catalog/templates/dataset-template.html
This PR:
- hides fields, including properties, journal, and grant description, if they are not populated, to prevent empty properties from making the rendered page ugly
- improves parsing of objects and arrays in the additional display tab so that they can be rendered in a more visually pleasing way.
**Example 1:**
New:
vs old:
**Example 2:**
New:
vs old
**Example 3:**
New:
vs old:
> Fine tuning of HTML rendering

- datalad_catalog/catalog/assets/app_component_dataset.js
- datalad_catalog/catalog/assets/app_component_item.js
- datalad_catalog/catalog/assets/style.css
- datalad_catalog/catalog/templates/dataset-template.html
- datalad_catalog/catalog/templates/item-template.html
This PR:
- Display last updated as 'unknown' if the corresponding field is empty (previously an empty value was displayed as an ugly 'NaN')
- For items in the content tab:
- The cloud icon as a means to download a file is removed
- filename is turned into a link, if the file has an associated URL and only if the URL string contains `http`
- the file size is updated to display correctly (empty string, and not NaN, if the value is empty)
- the cursor will only turn into a pointer if the item is a folder or a file with a link.
- closes https://github.com/datalad/datalad-catalog/issues/332
- closes https://github.com/datalad/datalad-catalog/issues/361
> ENH: UI/UX

- datalad_catalog/catalog/assets/app_component_dataset.js
- datalad_catalog/catalog/assets/app_component_item.js
- datalad_catalog/catalog/templates/dataset-template.html
- datalad_catalog/catalog/templates/item-template.html
This PR:
- Fixes subdataset filtering to filter on `name`, `givenName`, and `familyName` _provided that the property value in each case is not null_
- closes https://github.com/datalad/datalad-catalog/issues/291
- Update subdataset filtering behaviour to only show filtering options when the number of subdatasets > 3. This will hide the filtering options otherwise. Additionally, if the filtering options are hidden, the tags on each subdataset will be deactivated (still visible, but not clickable)
- closes https://github.com/datalad/datalad-catalog/issues/370
- Clears filtering options (filtering text, selected filter tags) when navigating to a subdataset, both from the subdataset view and the content aka file tree view. This prevents the filtering options from remaining and subsequently …
> Update functionality wrt subdataset display / behaviour / filtering

- datalad_catalog/schema_utils.py
- datalad_catalog/tests/test_schema_utils.py
This is particularly useful when wanting to get a base structure with minimal fields that also exclude required fields, e.g. a file-level metadata item with all required fields except for 'path' which will be filled at a later stage.
> Adds ability for schema_utils to return a base metadata item with specific keys excluded

- datalad_catalog/catalog/assets/app_component_dataset.js
This adds improved logic to the function called when user selects the home button: (this applies when the current location is any tab on any dataset page in a catalog)
- If there is NO home page set:
- if there is a tab name in the URL, navigate to current
- else: don't navigate, only reset
- If there IS a home page set:
- if the current page IS the home page:
- if there is a tab name in the URL, navigate to current
- else: don't navigate, only reset
- if the current page is NOT the home page, navigate to home (reset = clear filters and set tab index = 0)
Closes https://github.com/datalad/datalad-catalog/issues/390
> ENH: Updates functioning of catalog home button

- datalad_catalog/catalog/assets/app_component_dataset.js
- datalad_catalog/catalog/metadata/deabeb9b-7a37-4062-a1e0-8fcef7909609/6d7fb68264f9b9951ae141fc830712a8744e3293/config.json
- datalad_catalog/catalog/templates/dataset-template.html
This is a development in response to https://github.com/psychoinformatics-de/sfb1451-projects-catalog/issues/36
This introduces several changes, including:
- the content tab is displayed in position 0
- the subdatasets tab is displayed in position 1
- other standard / non-standard tabs follow in their original order
- if no default tab is specified via the dataset-level config, the content tab is shown
- if a different default tab is provided via dataset-level config, that tab will be shown
- the default tab will be shown on:
- navigation to dataset via URL
- navigation to dataset from within the catalog web app
- navigation to superdataset via user pressing the home button
- a new config file is added for the demo superdataset, with subdatasets as the default tab
Demo at: …
> Adds ability to specify default tab display via dataset-level config file

- datalad_catalog/catalog/assets/display_schema.js
This fixes the issue where the `jsonschema_metadata_sources` could not be displayed when clicked.
> Fix double underscore typo in display_schema javascript

- datalad_catalog/catalog/assets/app_component_dataset.js
- datalad_catalog/catalog/assets/app_globals.js
- datalad_catalog/catalog/assets/app_router.js
- datalad_catalog/catalog/display_schema.html
- datalad_catalog/catalog/index.html
- datalad_catalog/catalog/templates/dataset-template.html
- datalad_catalog/webcatalog.py
This includes several diffs, including some patches dealing with the fallout:
- Changes the vue-router configuration from hash mode to history mode in order to remove the # in the URL which makes google crawling difficult.
- As a necessary consequence, updates all html and js pages with changes relating to the relative location of files; now everything is relative to root, i.e. starts with '/'.
- Fixes the backbutton display which started being buggy after the change to history mode.
- Adds an href property to all subdataset links on all dataset pages, so that they can be more easily crawlable by google.
- Add structured and linked data in json-ld format to the html document head for each dataset, which makes a dataset page show rich metadata in google's dataset search.
- Update local …
> Changes to vue router history mode in order to improve SEO

- datalad_catalog/catalog/assets/app.js
- datalad_catalog/catalog/assets/app_component_dataset.js
- datalad_catalog/catalog/assets/app_globals.js
- datalad_catalog/catalog/config.json
- datalad_catalog/config/config.json
- datalad_catalog/tests/test_config.py
The goal here is to not only provide the minimum required fields to make a catalog dataset discoverable by google dataset search (this is already possible) but to now also include any optional fields to enrich the structured data for the dataset when  viewing it in a dataset search result.
The changes necessary to allow this include:
- basic functions to map all optional fields from existing properties in a metadata entry
- an update to the catalog-level config file to include fields for `catalog_name` and `catalog_url` that are used for mapping to the optional `includedInDataCatalog` rich data field
Any existing or new catalog that wants to make use of these features should ensure that their catalog-level config file is updated.
> Rich data enrichment v2

- datalad_catalog/catalog/assets/app_component_dataset.js
I think (but please verify) that these two lines should be removed, because the actual handling of "homepage" seems to happen a few lines above, and uses optional chaining (`?.`). If left in, they cause errors when the additional display does not contain "homepage".
This should fix #450
> Remove void statement which can cause errors

- datalad_catalog/catalog/assets/app_component_dataset.js
- tools/create_alias_concept_metadata.py
This PR fixes errors in handling custom notebook information (the ability was introduced as part of #440). No tracing issue because the fixes are small.
It also fixes a black formatting inconsistency picked by CI (2024 stable style requires empty line after module docstring) also seen in a few recent PRs.
See Individual commits for details.
> Fix notebook handling

- datalad_catalog/catalog/templates/dataset-template.html
Fixes #466 
This PR adds a missing `/` to the content of `Full URL` in the share-pop up of a dataset landing page in the catalog
> Add missing `/` to `Full URL` 

- README.md
- docs/source/index.rst
Might be a good idea to duplicate the same text in the docs...
Closes https://github.com/datalad/datalad-catalog/issues/468
> Add notice about new development direction for catalog

- README.md
- requirements-devel.txt
Adds black as development requirement and explains how to run linting tests locally before creating a PR
Closes #124
> Docs and dependency for linting

- datalad_catalog/__init__.py
- datalad_catalog/tree.py
- docs/source/command_line_reference.rst
- docs/source/python_module_reference.rst
This new command prints the "dataset-version tree" of a catalog, i.e. all datasets included in a catalog, and all versions of those datasets. Closes https://github.com/datalad/datalad-catalog/issues/441
> New `tree` command

- datalad_catalog/catalog/assets/app_component_dataset.js
- datalad_catalog/catalog/metadata/deabeb9b-7a37-4062-a1e0-8fcef7909609/6d7fb68264f9b9951ae141fc830712a8744e3293/config.json
- datalad_catalog/catalog/metadata/deabeb9b-7a37-4062-a1e0-8fcef7909609/6d7fb68264f9b9951ae141fc830712a8744e3293/ddb/8aa081e7afeb3831fe007a3816dce.json
- datalad_catalog/catalog/schema/jsonschema_dataset.json
- datalad_catalog/catalog/templates/dataset-template.html
- datalad_catalog/config/config.json
- datalad_catalog/tests/test_schema_utils.py
These two fields are new properties in the dataset schema, and allow dissociation from the existing `url` field, which is specific to a datalad dataset. The visibility of these buttons can also be controlled via associated show/hide fields in the catalog or dataset-level config. The demo dataset config and metadata has been updated to demonstrate the homepage button, and the default config has been updated to include the new controlling flags.
> Introduce `download_url` and `homepage_url` with associated buttons

- datalad_catalog/workflow.py
This changes the argument name from `type` to `mode` in order to prevent any confusion (on the part of the python interpreter) between the argparse argument `type` and some possibly protected variable `type`.
Addresses part of https://github.com/datalad/datalad-catalog/issues/435
> Fix error caused by argument name 'type' confusion

- README.md
- docs/source/catalog_schema.rst
The README links to the demo catalog instance in several places, mostly to the schema view. Since the demo moved from GitHub Pages to Netlify (#421), these links needed to be updated.
Ping #422
Edit: closes #488
> Replace links to GitHub Pages with Netlify README
