datalad/datalad-catalog

.github/workflows/docbuild.yml, .github/workflows/test_crippledfs.yml, datalad_catalog/catalog.py, datalad_catalog/templates/jsonschema_authors.json, datalad_catalog/templates/jsonschema_catalog.json, datalad_catalog/templates/jsonschema_dataset.json, datalad_catalog/templates/jsonschema_file.json, datalad_catalog/tests/data/catalog_metadata_valid.json, datalad_catalog/tests/test_schema.py, datalad_catalog/webcatalog.py, docs/source/command_line_reference.rst, requirements-devel.txt, setup.cfg
Addresses https://github.com/datalad/datalad-catalog/issues/48
Decided to go with option outlined in https://github.com/datalad/datalad-catalog/issues/48#issuecomment-1120261209
Cn be changed in future if required.
=> Fix validation

datalad_catalog/catalog.py
tests are already included in tests/test_validation.py
=> adds validate-only option to catalog actions

docs/source/command_line_reference.rst
=> DOC: add datalad-catalog back to the command line ref

requirements-devel.txt, setup.cfg
The PR replaces an erroneous dependency on 'yaml2' with a dependency on 'pyyaml'.
=> Fix yaml dependency

datalad_catalog/meta_item.py, datalad_catalog/tests/test_multisource.py, datalad_catalog/tests/test_node.py, datalad_catalog/webcatalog.py
This fixes a typo in an internal method name.
=> RF/Typos: add_attribrutes -> add_attributes

datalad_catalog/tests/test_action_add.py, datalad_catalog/tests/test_action_create.py, datalad_catalog/tests/test_action_setsuper.py, datalad_catalog/tests/test_catalog.py, datalad_catalog/tests/test_catalog_arguments.py, datalad_catalog/tests/test_config.py, datalad_catalog/tests/test_multisource.py, datalad_catalog/tests/test_node.py, datalad_catalog/tests/test_schema.py, datalad_catalog/tests/test_translate.py, datalad_catalog/tests/test_utils.py, datalad_catalog/tests/test_webcatalog.py
I found more import statements that could be cleaned up according to the design docs.
=> MNT: Clean up more import sections

.github/workflows/deploy_demo.yml
Closes https://github.com/datalad/datalad-catalog/issues/22
=> INFRA: Adds workflow to push demo catalog changes to `gh-pages`

.github/workflows/test_crippledfs.yml, datalad_catalog/extractors/datacite_gin.py, datalad_catalog/extractors/tests/test_datacite_gin.py
Fixes issue #131 
This PR cleans up the datacite_gin extractor and fixes its `get_required_content()` method to properly fetch the content that it requires.
=> Refactor, clean up, and fix datacite gin extractor

requirements-devel.txt, setup.cfg
=> ENH: depend on datalad 0.17

datalad_catalog/meta_item.py
=> Fixes bug of subdatasets not propagating to catalog metadata

datalad_catalog/catalog/assets/vue_app.js
=> Fixes "length of undefined" issue

datalad_catalog/catalog/assets/vue_app.js
This PR addresses:
- Web asset cleanup, specifically JS, using https://prettier.io/. Part of #107 
- Incorrect url resolving in #137
=> ENH: javascript asset styling and small fixes

README.md
Found #160 and thought to contribute the github action workflow badges
=> DOC: Add GH-action status badges

README.md, datalad_catalog/catalog/assets/style.css, datalad_catalog/catalog/assets/vue_app.js, datalad_catalog/catalog/index.html
This PR:
- Updates the README to include workflow functionality
- closes https://github.com/datalad/datalad-catalog/issues/201
- closes https://github.com/datalad/datalad-catalog/issues/61
- closes https://github.com/datalad/datalad-catalog/issues/66
=> DOC+BF+NF: readme update + javascript tweaks

datalad_catalog/schema/jsonschema_dataset.json
=> ENH: add icon field to additional display property

.appveyor.yml, .github/workflows/test_crippledfs.yml, requirements-devel.txt
Reverts datalad/datalad-catalog#213
See https://github.com/datalad/datalad-catalog/pull/213#issuecomment-1324777561
=> Revert "Make test github workflow test in both normal and crippled tmp scenarios"

datalad_catalog/catalog/assets/jsonschema_authors.json, datalad_catalog/catalog/assets/jsonschema_dataset.json, datalad_catalog/catalog/assets/jsonschema_extractors.json, datalad_catalog/catalog/assets/jsonschema_file.json, datalad_catalog/schema/jsonschema_authors.json, datalad_catalog/schema/jsonschema_dataset.json, datalad_catalog/schema/jsonschema_extractors.json, datalad_catalog/schema/jsonschema_file.json
=> ENH: add titles to all object properties in schemas

docs/source/pipeline_description.rst
Addresses the outdated documentation mentioned https://github.com/datalad/datalad-catalog/issues/244
=> DOC: update pipeline docs to agree with latest version of meta-conduct use

datalad_catalog/translators/bids_dataset_translator.py
Fixes https://github.com/datalad/datalad-catalog/issues/267
=> ENH: Translator edits

datalad_catalog/catalog/assets/app_component_dataset.js, datalad_catalog/catalog/assets/app_component_item.js, datalad_catalog/catalog/assets/style.css, datalad_catalog/catalog/index.html, datalad_catalog/catalog/templates/dataset-template.html, datalad_catalog/catalog/templates/item-template.html
This PR adds some nice-to-have functionality:
- https://github.com/datalad/datalad-catalog/issues/280
- https://github.com/datalad/datalad-catalog/issues/288
- https://github.com/datalad/datalad-catalog/issues/287
=> UX: improve user experience when browsing

datalad_catalog/catalog/assets/app_component_dataset.js, datalad_catalog/catalog/templates/dataset-template.html
This PR closes:
- https://github.com/datalad/datalad-catalog/issues/300
- https://github.com/datalad/datalad-catalog/issues/292
=> ENH+BF: Bring back the dead

README.md, docs/source/conf.py, docs/source/index.rst
Closes https://github.com/datalad/datalad-catalog/issues/307
=> ENH: adds acknowledgements to readme and docs

CHANGELOG.md
Fixing merge conflicts for new release
=> 1.0.0 release

datalad_catalog/catalog/assets/app_globals.js
This is a minor edit of https://github.com/datalad/datalad-catalog/pull/413/commits/531cfad93827712ee4131b1482611da9d9b6e7b1
=> Define default social links in javascript instead of making them null

README.md, docs/source/index.rst
Fixes:
- demo site link in docs
- outdated tutorial link in readme
- outdated command syntax in readme
Closes https://github.com/datalad/datalad-catalog/issues/428
=> Fix outdated docs

datalad_catalog/catalog/templates/dataset-template.html, datalad_catalog/extractors/catalog_core.py, datalad_catalog/extractors/catalog_runprov.py
In response to https://github.com/sfb1451/metadata-catalog/issues/94
Also related to https://github.com/datalad/datalad-catalog/issues/37
=> Small tweaks to rendering of runprov records
